---
title: "HW6"
author: "Jacob Moore"
date: "4/4/2022"
output: html_document
---

install.packages("ggplot2movies")
library(ggplot2movies)
library(ggplot2)
library(ggrepel)
library(cowplot)
library(tidyr)
library(dplyr)
library(ggridges)
library(colorspace)
library(stringr)
library(forcats)

#2a
load("~/Documents/house_prices.rda")
prices = house_prices
ggplot(data=prices, aes(x=date, y=house_price_index)) +
  geom_smooth() + facet_wrap(~state, ncol = 10) +
  scale_x_date(date_breaks = "15 years", date_labels = c("20", "80", "00"))

ggplot(data=prices, aes(x=date, y=house_price_index)) +
  geom_smooth() +
  facet_wrap(~state, ncol = 10) +
  scale_x_date(name="Year", date_breaks = '20 years', date_labels = '%y', limits = as.Date(c('1964-01-01', '2026-01-01'), 
              breaks = as.Date(c('1980-01-01', '2020-01-01'))))             

#2b
house_reshaped = gather(prices, measure, value, -date, -state, -house_price_perc)

#2c
ggplot(data = house_reshaped, aes(x=date, y=value, group=measure)) +
  geom_smooth() +
  facet_wrap(~state, ncol = 10) +
  scale_x_date(name='Year', date_breaks = '20 years', date_labels = '%y', limits = as.Date(c('1964-01-01', '2026-01-01'), breaks = as.Date(c('1980-01-01', '2020-01-01'))))
#I do not think that this is a good graph to represent this information because there is barely 
#any noticable fluctuation in the unemployment percentage group.
